[package]
name = "rsawesome"
version = "0.1.0"
authors = ["yangrui <yangrui9512@126.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
typename = "0.1.1"
mysql = "*" 
chrono = "0.4"
